version: '3.8'
services:
  jupyter:
    build: .
    container_name: jupyter_py38
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes 